# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meteoalign/ui/catalog_download_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CatalogDownloadDialog(object):
    def setupUi(self, CatalogDownloadDialog):
        CatalogDownloadDialog.setObjectName("CatalogDownloadDialog")
        CatalogDownloadDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        CatalogDownloadDialog.resize(460, 150)
        self.verticalLayout = QtWidgets.QVBoxLayout(CatalogDownloadDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelStatus = QtWidgets.QLabel(CatalogDownloadDialog)
        self.labelStatus.setWordWrap(True)
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout.addWidget(self.labelStatus)
        self.progressBar = QtWidgets.QProgressBar(CatalogDownloadDialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayoutButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayoutButtons.setObjectName("horizontalLayoutButtons")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutButtons.addItem(spacerItem)
        self.pushButtonClose = QtWidgets.QPushButton(CatalogDownloadDialog)
        self.pushButtonClose.setEnabled(False)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.horizontalLayoutButtons.addWidget(self.pushButtonClose)
        self.verticalLayout.addLayout(self.horizontalLayoutButtons)

        self.retranslateUi(CatalogDownloadDialog)
        QtCore.QMetaObject.connectSlotsByName(CatalogDownloadDialog)

    def retranslateUi(self, CatalogDownloadDialog):
        _translate = QtCore.QCoreApplication.translate
        CatalogDownloadDialog.setWindowTitle(_translate("CatalogDownloadDialog", "下载星表"))
        self.labelStatus.setText(_translate("CatalogDownloadDialog", "准备下载星表..."))
        self.pushButtonClose.setText(_translate("CatalogDownloadDialog", "关闭"))
