# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meteoalign/ui/image_group_reference_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageGroupReferenceDialog(object):
    def setupUi(self, ImageGroupReferenceDialog):
        ImageGroupReferenceDialog.setObjectName("ImageGroupReferenceDialog")
        ImageGroupReferenceDialog.resize(440, 560)
        ImageGroupReferenceDialog.setMinimumSize(QtCore.QSize(250, 360))
        ImageGroupReferenceDialog.setMaximumSize(QtCore.QSize(480, 16777215))
        self.verticalLayoutImageGroupReference = QtWidgets.QVBoxLayout(ImageGroupReferenceDialog)
        self.verticalLayoutImageGroupReference.setObjectName("verticalLayoutImageGroupReference")
        self.labelImageGroupHint = QtWidgets.QLabel(ImageGroupReferenceDialog)
        self.labelImageGroupHint.setWordWrap(True)
        self.labelImageGroupHint.setObjectName("labelImageGroupHint")
        self.verticalLayoutImageGroupReference.addWidget(self.labelImageGroupHint)
        self.tableWidgetImageGroup = QtWidgets.QTableWidget(ImageGroupReferenceDialog)
        self.tableWidgetImageGroup.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetImageGroup.setAlternatingRowColors(True)
        self.tableWidgetImageGroup.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidgetImageGroup.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetImageGroup.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidgetImageGroup.setRowCount(0)
        self.tableWidgetImageGroup.setColumnCount(5)
        self.tableWidgetImageGroup.setObjectName("tableWidgetImageGroup")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetImageGroup.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetImageGroup.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetImageGroup.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetImageGroup.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetImageGroup.setHorizontalHeaderItem(4, item)
        self.tableWidgetImageGroup.horizontalHeader().setStretchLastSection(False)
        self.tableWidgetImageGroup.verticalHeader().setVisible(False)
        self.verticalLayoutImageGroupReference.addWidget(self.tableWidgetImageGroup)

        self.retranslateUi(ImageGroupReferenceDialog)
        QtCore.QMetaObject.connectSlotsByName(ImageGroupReferenceDialog)

    def retranslateUi(self, ImageGroupReferenceDialog):
        _translate = QtCore.QCoreApplication.translate
        ImageGroupReferenceDialog.setWindowTitle(_translate("ImageGroupReferenceDialog", "从图像组中选取参考"))
        self.labelImageGroupHint.setText(_translate("ImageGroupReferenceDialog", "双击某一行以选取参考图像。"))
        item = self.tableWidgetImageGroup.horizontalHeaderItem(0)
        item.setText(_translate("ImageGroupReferenceDialog", "文件名"))
        item = self.tableWidgetImageGroup.horizontalHeaderItem(1)
        item.setText(_translate("ImageGroupReferenceDialog", "匹配"))
        item = self.tableWidgetImageGroup.horizontalHeaderItem(2)
        item.setText(_translate("ImageGroupReferenceDialog", "映射"))
        item = self.tableWidgetImageGroup.horizontalHeaderItem(3)
        item.setText(_translate("ImageGroupReferenceDialog", "蒙版"))
        item = self.tableWidgetImageGroup.horizontalHeaderItem(4)
        item.setText(_translate("ImageGroupReferenceDialog", "预览"))
