# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meteoalign/ui/image_group_assistant_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageGroupAssistantDialog(object):
    def setupUi(self, ImageGroupAssistantDialog):
        ImageGroupAssistantDialog.setObjectName("ImageGroupAssistantDialog")
        ImageGroupAssistantDialog.resize(352, 560)
        ImageGroupAssistantDialog.setMinimumSize(QtCore.QSize(250, 360))
        ImageGroupAssistantDialog.setMaximumSize(QtCore.QSize(390, 16777215))
        self.verticalLayoutImageGroupAssistant = QtWidgets.QVBoxLayout(ImageGroupAssistantDialog)
        self.verticalLayoutImageGroupAssistant.setObjectName("verticalLayoutImageGroupAssistant")
        self.labelImageGroupHint = QtWidgets.QLabel(ImageGroupAssistantDialog)
        self.labelImageGroupHint.setWordWrap(True)
        self.labelImageGroupHint.setObjectName("labelImageGroupHint")
        self.verticalLayoutImageGroupAssistant.addWidget(self.labelImageGroupHint)
        self.tableWidgetImageGroup = QtWidgets.QTableWidget(ImageGroupAssistantDialog)
        self.tableWidgetImageGroup.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidgetImageGroup.setAlternatingRowColors(True)
        self.tableWidgetImageGroup.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidgetImageGroup.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetImageGroup.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidgetImageGroup.setRowCount(0)
        self.tableWidgetImageGroup.setColumnCount(3)
        self.tableWidgetImageGroup.setObjectName("tableWidgetImageGroup")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetImageGroup.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetImageGroup.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetImageGroup.setHorizontalHeaderItem(2, item)
        self.tableWidgetImageGroup.horizontalHeader().setStretchLastSection(False)
        self.tableWidgetImageGroup.verticalHeader().setVisible(False)
        self.verticalLayoutImageGroupAssistant.addWidget(self.tableWidgetImageGroup)

        self.retranslateUi(ImageGroupAssistantDialog)
        QtCore.QMetaObject.connectSlotsByName(ImageGroupAssistantDialog)

    def retranslateUi(self, ImageGroupAssistantDialog):
        _translate = QtCore.QCoreApplication.translate
        ImageGroupAssistantDialog.setWindowTitle(_translate("ImageGroupAssistantDialog", "图像组助手"))
        self.labelImageGroupHint.setText(_translate("ImageGroupAssistantDialog", "双击任意图像，切换到该图像继续星点匹配。"))
        item = self.tableWidgetImageGroup.horizontalHeaderItem(0)
        item.setText(_translate("ImageGroupAssistantDialog", "文件名"))
        item = self.tableWidgetImageGroup.horizontalHeaderItem(1)
        item.setText(_translate("ImageGroupAssistantDialog", "匹配"))
        item = self.tableWidgetImageGroup.horizontalHeaderItem(2)
        item.setText(_translate("ImageGroupAssistantDialog", "映射"))
