# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meteoalign/ui/mapping_validation_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MappingValidationDialog(object):
    def setupUi(self, MappingValidationDialog):
        MappingValidationDialog.setObjectName("MappingValidationDialog")
        MappingValidationDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(MappingValidationDialog)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayoutControls = QtWidgets.QHBoxLayout()
        self.horizontalLayoutControls.setObjectName("horizontalLayoutControls")
        self.checkBoxOverlayEnabled = QtWidgets.QCheckBox(MappingValidationDialog)
        self.checkBoxOverlayEnabled.setChecked(True)
        self.checkBoxOverlayEnabled.setObjectName("checkBoxOverlayEnabled")
        self.horizontalLayoutControls.addWidget(self.checkBoxOverlayEnabled)
        self.labelImageOpacity = QtWidgets.QLabel(MappingValidationDialog)
        self.labelImageOpacity.setObjectName("labelImageOpacity")
        self.horizontalLayoutControls.addWidget(self.labelImageOpacity)
        self.doubleSpinBoxImageOpacity = QtWidgets.QDoubleSpinBox(MappingValidationDialog)
        self.doubleSpinBoxImageOpacity.setDecimals(1)
        self.doubleSpinBoxImageOpacity.setMinimum(0.0)
        self.doubleSpinBoxImageOpacity.setMaximum(100.0)
        self.doubleSpinBoxImageOpacity.setSingleStep(5.0)
        self.doubleSpinBoxImageOpacity.setProperty("value", 55.0)
        self.doubleSpinBoxImageOpacity.setObjectName("doubleSpinBoxImageOpacity")
        self.horizontalLayoutControls.addWidget(self.doubleSpinBoxImageOpacity)
        self.labelGridPrecision = QtWidgets.QLabel(MappingValidationDialog)
        self.labelGridPrecision.setObjectName("labelGridPrecision")
        self.horizontalLayoutControls.addWidget(self.labelGridPrecision)
        self.spinBoxGridPrecision = QtWidgets.QSpinBox(MappingValidationDialog)
        self.spinBoxGridPrecision.setMinimum(12)
        self.spinBoxGridPrecision.setMaximum(180)
        self.spinBoxGridPrecision.setProperty("value", 64)
        self.spinBoxGridPrecision.setObjectName("spinBoxGridPrecision")
        self.horizontalLayoutControls.addWidget(self.spinBoxGridPrecision)
        self.pushButtonResolveGrid = QtWidgets.QPushButton(MappingValidationDialog)
        self.pushButtonResolveGrid.setObjectName("pushButtonResolveGrid")
        self.horizontalLayoutControls.addWidget(self.pushButtonResolveGrid)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutControls.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayoutControls)
        self.graphicsViewValidation = QtWidgets.QGraphicsView(MappingValidationDialog)
        self.graphicsViewValidation.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsViewValidation.setDragMode(QtWidgets.QGraphicsView.NoDrag)
        self.graphicsViewValidation.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.graphicsViewValidation.setResizeAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.graphicsViewValidation.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.graphicsViewValidation.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsViewValidation.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsViewValidation.setObjectName("graphicsViewValidation")
        self.verticalLayout.addWidget(self.graphicsViewValidation)

        self.retranslateUi(MappingValidationDialog)
        QtCore.QMetaObject.connectSlotsByName(MappingValidationDialog)

    def retranslateUi(self, MappingValidationDialog):
        _translate = QtCore.QCoreApplication.translate
        MappingValidationDialog.setWindowTitle(_translate("MappingValidationDialog", "映射验证"))
        self.checkBoxOverlayEnabled.setText(_translate("MappingValidationDialog", "叠加显示"))
        self.labelImageOpacity.setText(_translate("MappingValidationDialog", "图像透明度"))
        self.doubleSpinBoxImageOpacity.setSuffix(_translate("MappingValidationDialog", " %"))
        self.labelGridPrecision.setText(_translate("MappingValidationDialog", "网格精度"))
        self.spinBoxGridPrecision.setSuffix(_translate("MappingValidationDialog", " 点/长边"))
        self.pushButtonResolveGrid.setText(_translate("MappingValidationDialog", "重新求解"))
