# -*- coding: utf-8 -*-

# 此文件由 meteoalign/ui/main_window.ui 生成。
#
# 生成工具：PyQt5 UI code generator 5.15.11
#
# 注意：再次运行 pyuic5 时，手动修改会被覆盖。


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 820)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutMain = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayoutMain.setObjectName("verticalLayoutMain")
        self.tabWidgetMain = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetMain.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidgetMain.setObjectName("tabWidgetMain")
        self.tabSimulator = QtWidgets.QWidget()
        self.tabSimulator.setObjectName("tabSimulator")
        self.horizontalLayoutSimulator = QtWidgets.QHBoxLayout(self.tabSimulator)
        self.horizontalLayoutSimulator.setObjectName("horizontalLayoutSimulator")
        self.scrollAreaControls = QtWidgets.QScrollArea(self.tabSimulator)
        self.scrollAreaControls.setMinimumSize(QtCore.QSize(330, 0))
        self.scrollAreaControls.setMaximumSize(QtCore.QSize(390, 16777215))
        self.scrollAreaControls.setWidgetResizable(True)
        self.scrollAreaControls.setObjectName("scrollAreaControls")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 368, 900))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutControls = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayoutControls.setObjectName("verticalLayoutControls")
        self.groupBoxObserver = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxObserver.setObjectName("groupBoxObserver")
        self.formLayoutObserver = QtWidgets.QFormLayout(self.groupBoxObserver)
        self.formLayoutObserver.setObjectName("formLayoutObserver")
        self.labelObservationTime = QtWidgets.QLabel(self.groupBoxObserver)
        self.labelObservationTime.setObjectName("labelObservationTime")
        self.formLayoutObserver.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelObservationTime)
        self.dateTimeEditObservation = QtWidgets.QDateTimeEdit(self.groupBoxObserver)
        self.dateTimeEditObservation.setCalendarPopup(True)
        self.dateTimeEditObservation.setObjectName("dateTimeEditObservation")
        self.formLayoutObserver.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateTimeEditObservation)
        self.labelUtcOffset = QtWidgets.QLabel(self.groupBoxObserver)
        self.labelUtcOffset.setObjectName("labelUtcOffset")
        self.formLayoutObserver.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelUtcOffset)
        self.doubleSpinBoxUtcOffset = QtWidgets.QDoubleSpinBox(self.groupBoxObserver)
        self.doubleSpinBoxUtcOffset.setMinimum(-12.0)
        self.doubleSpinBoxUtcOffset.setMaximum(14.0)
        self.doubleSpinBoxUtcOffset.setSingleStep(0.5)
        self.doubleSpinBoxUtcOffset.setObjectName("doubleSpinBoxUtcOffset")
        self.formLayoutObserver.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxUtcOffset)
        self.labelLatitude = QtWidgets.QLabel(self.groupBoxObserver)
        self.labelLatitude.setObjectName("labelLatitude")
        self.formLayoutObserver.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelLatitude)
        self.doubleSpinBoxLatitude = QtWidgets.QDoubleSpinBox(self.groupBoxObserver)
        self.doubleSpinBoxLatitude.setDecimals(6)
        self.doubleSpinBoxLatitude.setMinimum(-90.0)
        self.doubleSpinBoxLatitude.setMaximum(90.0)
        self.doubleSpinBoxLatitude.setObjectName("doubleSpinBoxLatitude")
        self.formLayoutObserver.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxLatitude)
        self.labelLongitude = QtWidgets.QLabel(self.groupBoxObserver)
        self.labelLongitude.setObjectName("labelLongitude")
        self.formLayoutObserver.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelLongitude)
        self.doubleSpinBoxLongitude = QtWidgets.QDoubleSpinBox(self.groupBoxObserver)
        self.doubleSpinBoxLongitude.setDecimals(6)
        self.doubleSpinBoxLongitude.setMinimum(-180.0)
        self.doubleSpinBoxLongitude.setMaximum(180.0)
        self.doubleSpinBoxLongitude.setObjectName("doubleSpinBoxLongitude")
        self.formLayoutObserver.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxLongitude)
        self.labelElevation = QtWidgets.QLabel(self.groupBoxObserver)
        self.labelElevation.setObjectName("labelElevation")
        self.formLayoutObserver.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelElevation)
        self.doubleSpinBoxElevation = QtWidgets.QDoubleSpinBox(self.groupBoxObserver)
        self.doubleSpinBoxElevation.setMinimum(-500.0)
        self.doubleSpinBoxElevation.setMaximum(9000.0)
        self.doubleSpinBoxElevation.setObjectName("doubleSpinBoxElevation")
        self.formLayoutObserver.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxElevation)
        self.verticalLayoutControls.addWidget(self.groupBoxObserver)
        self.groupBoxCamera = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxCamera.setObjectName("groupBoxCamera")
        self.formLayoutCamera = QtWidgets.QFormLayout(self.groupBoxCamera)
        self.formLayoutCamera.setObjectName("formLayoutCamera")
        self.labelSensorWidth = QtWidgets.QLabel(self.groupBoxCamera)
        self.labelSensorWidth.setObjectName("labelSensorWidth")
        self.formLayoutCamera.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelSensorWidth)
        self.doubleSpinBoxSensorWidth = QtWidgets.QDoubleSpinBox(self.groupBoxCamera)
        self.doubleSpinBoxSensorWidth.setMinimum(1.0)
        self.doubleSpinBoxSensorWidth.setMaximum(200.0)
        self.doubleSpinBoxSensorWidth.setObjectName("doubleSpinBoxSensorWidth")
        self.formLayoutCamera.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxSensorWidth)
        self.labelSensorHeight = QtWidgets.QLabel(self.groupBoxCamera)
        self.labelSensorHeight.setObjectName("labelSensorHeight")
        self.formLayoutCamera.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelSensorHeight)
        self.doubleSpinBoxSensorHeight = QtWidgets.QDoubleSpinBox(self.groupBoxCamera)
        self.doubleSpinBoxSensorHeight.setMinimum(1.0)
        self.doubleSpinBoxSensorHeight.setMaximum(200.0)
        self.doubleSpinBoxSensorHeight.setObjectName("doubleSpinBoxSensorHeight")
        self.formLayoutCamera.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxSensorHeight)
        self.pushButtonSwapOrientation = QtWidgets.QPushButton(self.groupBoxCamera)
        self.pushButtonSwapOrientation.setObjectName("pushButtonSwapOrientation")
        self.formLayoutCamera.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.pushButtonSwapOrientation)
        self.labelImageWidth = QtWidgets.QLabel(self.groupBoxCamera)
        self.labelImageWidth.setObjectName("labelImageWidth")
        self.formLayoutCamera.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelImageWidth)
        self.spinBoxImageWidth = QtWidgets.QSpinBox(self.groupBoxCamera)
        self.spinBoxImageWidth.setMinimum(128)
        self.spinBoxImageWidth.setMaximum(20000)
        self.spinBoxImageWidth.setObjectName("spinBoxImageWidth")
        self.formLayoutCamera.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBoxImageWidth)
        self.labelImageHeight = QtWidgets.QLabel(self.groupBoxCamera)
        self.labelImageHeight.setObjectName("labelImageHeight")
        self.formLayoutCamera.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelImageHeight)
        self.spinBoxImageHeight = QtWidgets.QSpinBox(self.groupBoxCamera)
        self.spinBoxImageHeight.setMinimum(128)
        self.spinBoxImageHeight.setMaximum(20000)
        self.spinBoxImageHeight.setObjectName("spinBoxImageHeight")
        self.formLayoutCamera.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBoxImageHeight)
        self.labelFocalLength = QtWidgets.QLabel(self.groupBoxCamera)
        self.labelFocalLength.setObjectName("labelFocalLength")
        self.formLayoutCamera.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelFocalLength)
        self.doubleSpinBoxFocalLength = QtWidgets.QDoubleSpinBox(self.groupBoxCamera)
        self.doubleSpinBoxFocalLength.setDecimals(2)
        self.doubleSpinBoxFocalLength.setMinimum(1.0)
        self.doubleSpinBoxFocalLength.setMaximum(2000.0)
        self.doubleSpinBoxFocalLength.setObjectName("doubleSpinBoxFocalLength")
        self.formLayoutCamera.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxFocalLength)
        self.labelLensModel = QtWidgets.QLabel(self.groupBoxCamera)
        self.labelLensModel.setObjectName("labelLensModel")
        self.formLayoutCamera.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelLensModel)
        self.comboBoxLensModel = QtWidgets.QComboBox(self.groupBoxCamera)
        self.comboBoxLensModel.setObjectName("comboBoxLensModel")
        self.comboBoxLensModel.addItem("")
        self.comboBoxLensModel.addItem("")
        self.comboBoxLensModel.addItem("")
        self.formLayoutCamera.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBoxLensModel)
        self.labelFisheyeFov = QtWidgets.QLabel(self.groupBoxCamera)
        self.labelFisheyeFov.setObjectName("labelFisheyeFov")
        self.formLayoutCamera.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.labelFisheyeFov)
        self.doubleSpinBoxFisheyeFov = QtWidgets.QDoubleSpinBox(self.groupBoxCamera)
        self.doubleSpinBoxFisheyeFov.setDecimals(1)
        self.doubleSpinBoxFisheyeFov.setMinimum(30.0)
        self.doubleSpinBoxFisheyeFov.setMaximum(300.0)
        self.doubleSpinBoxFisheyeFov.setSingleStep(5.0)
        self.doubleSpinBoxFisheyeFov.setObjectName("doubleSpinBoxFisheyeFov")
        self.formLayoutCamera.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxFisheyeFov)
        self.labelMagLimit = QtWidgets.QLabel(self.groupBoxCamera)
        self.labelMagLimit.setObjectName("labelMagLimit")
        self.formLayoutCamera.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.labelMagLimit)
        self.doubleSpinBoxMagLimit = QtWidgets.QDoubleSpinBox(self.groupBoxCamera)
        self.doubleSpinBoxMagLimit.setDecimals(1)
        self.doubleSpinBoxMagLimit.setMinimum(-2.0)
        self.doubleSpinBoxMagLimit.setMaximum(9.0)
        self.doubleSpinBoxMagLimit.setSingleStep(0.5)
        self.doubleSpinBoxMagLimit.setObjectName("doubleSpinBoxMagLimit")
        self.formLayoutCamera.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxMagLimit)
        self.verticalLayoutControls.addWidget(self.groupBoxCamera)
        self.groupBoxDisplay = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxDisplay.setObjectName("groupBoxDisplay")
        self.formLayoutDisplay = QtWidgets.QFormLayout(self.groupBoxDisplay)
        self.formLayoutDisplay.setObjectName("formLayoutDisplay")
        self.labelCommonNameLimit = QtWidgets.QLabel(self.groupBoxDisplay)
        self.labelCommonNameLimit.setObjectName("labelCommonNameLimit")
        self.formLayoutDisplay.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelCommonNameLimit)
        self.widgetCommonNameLimit = QtWidgets.QWidget(self.groupBoxDisplay)
        self.widgetCommonNameLimit.setObjectName("widgetCommonNameLimit")
        self.horizontalLayoutCommonNameLimit = QtWidgets.QHBoxLayout(self.widgetCommonNameLimit)
        self.horizontalLayoutCommonNameLimit.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayoutCommonNameLimit.setObjectName("horizontalLayoutCommonNameLimit")
        self.horizontalSliderCommonNameLimit = QtWidgets.QSlider(self.widgetCommonNameLimit)
        self.horizontalSliderCommonNameLimit.setMinimum(-20)
        self.horizontalSliderCommonNameLimit.setMaximum(65)
        self.horizontalSliderCommonNameLimit.setSingleStep(1)
        self.horizontalSliderCommonNameLimit.setPageStep(5)
        self.horizontalSliderCommonNameLimit.setProperty("value", 10)
        self.horizontalSliderCommonNameLimit.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderCommonNameLimit.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSliderCommonNameLimit.setTickInterval(10)
        self.horizontalSliderCommonNameLimit.setObjectName("horizontalSliderCommonNameLimit")
        self.horizontalLayoutCommonNameLimit.addWidget(self.horizontalSliderCommonNameLimit)
        self.labelCommonNameLimitValue = QtWidgets.QLabel(self.widgetCommonNameLimit)
        self.labelCommonNameLimitValue.setMinimumSize(QtCore.QSize(64, 0))
        self.labelCommonNameLimitValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCommonNameLimitValue.setObjectName("labelCommonNameLimitValue")
        self.horizontalLayoutCommonNameLimit.addWidget(self.labelCommonNameLimitValue)
        self.formLayoutDisplay.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.widgetCommonNameLimit)
        self.verticalLayoutControls.addWidget(self.groupBoxDisplay)
        self.groupBoxView = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxView.setObjectName("groupBoxView")
        self.formLayoutView = QtWidgets.QFormLayout(self.groupBoxView)
        self.formLayoutView.setObjectName("formLayoutView")
        self.labelAz = QtWidgets.QLabel(self.groupBoxView)
        self.labelAz.setObjectName("labelAz")
        self.formLayoutView.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelAz)
        self.doubleSpinBoxAz = QtWidgets.QDoubleSpinBox(self.groupBoxView)
        self.doubleSpinBoxAz.setDecimals(2)
        self.doubleSpinBoxAz.setMinimum(0.0)
        self.doubleSpinBoxAz.setMaximum(359.99)
        self.doubleSpinBoxAz.setSingleStep(1.0)
        self.doubleSpinBoxAz.setObjectName("doubleSpinBoxAz")
        self.formLayoutView.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxAz)
        self.labelAlt = QtWidgets.QLabel(self.groupBoxView)
        self.labelAlt.setObjectName("labelAlt")
        self.formLayoutView.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelAlt)
        self.doubleSpinBoxAlt = QtWidgets.QDoubleSpinBox(self.groupBoxView)
        self.doubleSpinBoxAlt.setDecimals(2)
        self.doubleSpinBoxAlt.setMinimum(-90.0)
        self.doubleSpinBoxAlt.setMaximum(90.0)
        self.doubleSpinBoxAlt.setSingleStep(1.0)
        self.doubleSpinBoxAlt.setObjectName("doubleSpinBoxAlt")
        self.formLayoutView.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxAlt)
        self.labelRoll = QtWidgets.QLabel(self.groupBoxView)
        self.labelRoll.setObjectName("labelRoll")
        self.formLayoutView.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelRoll)
        self.doubleSpinBoxRoll = QtWidgets.QDoubleSpinBox(self.groupBoxView)
        self.doubleSpinBoxRoll.setDecimals(2)
        self.doubleSpinBoxRoll.setMinimum(-180.0)
        self.doubleSpinBoxRoll.setMaximum(180.0)
        self.doubleSpinBoxRoll.setObjectName("doubleSpinBoxRoll")
        self.formLayoutView.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxRoll)
        self.verticalLayoutControls.addWidget(self.groupBoxView)
        self.groupBoxReference = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBoxReference.setObjectName("groupBoxReference")
        self.verticalLayoutReference = QtWidgets.QVBoxLayout(self.groupBoxReference)
        self.verticalLayoutReference.setObjectName("verticalLayoutReference")
        self.formLayoutReference = QtWidgets.QFormLayout()
        self.formLayoutReference.setObjectName("formLayoutReference")
        self.labelReferenceStarCount = QtWidgets.QLabel(self.groupBoxReference)
        self.labelReferenceStarCount.setObjectName("labelReferenceStarCount")
        self.formLayoutReference.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelReferenceStarCount)
        self.spinBoxReferenceStarCount = QtWidgets.QSpinBox(self.groupBoxReference)
        self.spinBoxReferenceStarCount.setMinimum(3)
        self.spinBoxReferenceStarCount.setMaximum(40)
        self.spinBoxReferenceStarCount.setObjectName("spinBoxReferenceStarCount")
        self.formLayoutReference.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBoxReferenceStarCount)
        self.verticalLayoutReference.addLayout(self.formLayoutReference)
        self.pushButtonExportReference = QtWidgets.QPushButton(self.groupBoxReference)
        self.pushButtonExportReference.setObjectName("pushButtonExportReference")
        self.verticalLayoutReference.addWidget(self.pushButtonExportReference)
        self.verticalLayoutControls.addWidget(self.groupBoxReference)
        self.pushButtonRender = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButtonRender.setObjectName("pushButtonRender")
        self.verticalLayoutControls.addWidget(self.pushButtonRender)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutControls.addItem(spacerItem)
        self.scrollAreaControls.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutSimulator.addWidget(self.scrollAreaControls)
        self.starMapView = QtWidgets.QGraphicsView(self.tabSimulator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.starMapView.sizePolicy().hasHeightForWidth())
        self.starMapView.setSizePolicy(sizePolicy)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.starMapView.setBackgroundBrush(brush)
        self.starMapView.setDragMode(QtWidgets.QGraphicsView.NoDrag)
        self.starMapView.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.starMapView.setResizeAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.starMapView.setObjectName("starMapView")
        self.horizontalLayoutSimulator.addWidget(self.starMapView)
        self.tabWidgetMain.addTab(self.tabSimulator, "")
        self.tabReferenceImage = QtWidgets.QWidget()
        self.tabReferenceImage.setObjectName("tabReferenceImage")
        self.horizontalLayoutReferenceImage = QtWidgets.QHBoxLayout(self.tabReferenceImage)
        self.horizontalLayoutReferenceImage.setObjectName("horizontalLayoutReferenceImage")
        self.groupBoxImportedImage = QtWidgets.QGroupBox(self.tabReferenceImage)
        self.groupBoxImportedImage.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBoxImportedImage.setMaximumSize(QtCore.QSize(360, 16777215))
        self.groupBoxImportedImage.setObjectName("groupBoxImportedImage")
        self.verticalLayoutImportedImage = QtWidgets.QVBoxLayout(self.groupBoxImportedImage)
        self.verticalLayoutImportedImage.setObjectName("verticalLayoutImportedImage")
        self.formLayoutImportedImage = QtWidgets.QFormLayout()
        self.formLayoutImportedImage.setObjectName("formLayoutImportedImage")
        self.labelImportedImagePathTitle = QtWidgets.QLabel(self.groupBoxImportedImage)
        self.labelImportedImagePathTitle.setObjectName("labelImportedImagePathTitle")
        self.formLayoutImportedImage.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelImportedImagePathTitle)
        self.labelImportedImagePath = QtWidgets.QLabel(self.groupBoxImportedImage)
        self.labelImportedImagePath.setWordWrap(True)
        self.labelImportedImagePath.setObjectName("labelImportedImagePath")
        self.formLayoutImportedImage.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelImportedImagePath)
        self.labelImportedImageSizeTitle = QtWidgets.QLabel(self.groupBoxImportedImage)
        self.labelImportedImageSizeTitle.setObjectName("labelImportedImageSizeTitle")
        self.formLayoutImportedImage.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelImportedImageSizeTitle)
        self.labelImportedImageSize = QtWidgets.QLabel(self.groupBoxImportedImage)
        self.labelImportedImageSize.setObjectName("labelImportedImageSize")
        self.formLayoutImportedImage.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.labelImportedImageSize)
        self.labelImportedPreviewSizeTitle = QtWidgets.QLabel(self.groupBoxImportedImage)
        self.labelImportedPreviewSizeTitle.setObjectName("labelImportedPreviewSizeTitle")
        self.formLayoutImportedImage.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelImportedPreviewSizeTitle)
        self.labelImportedPreviewSize = QtWidgets.QLabel(self.groupBoxImportedImage)
        self.labelImportedPreviewSize.setObjectName("labelImportedPreviewSize")
        self.formLayoutImportedImage.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.labelImportedPreviewSize)
        self.labelImportedPreviewScaleTitle = QtWidgets.QLabel(self.groupBoxImportedImage)
        self.labelImportedPreviewScaleTitle.setObjectName("labelImportedPreviewScaleTitle")
        self.formLayoutImportedImage.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelImportedPreviewScaleTitle)
        self.labelImportedPreviewScale = QtWidgets.QLabel(self.groupBoxImportedImage)
        self.labelImportedPreviewScale.setObjectName("labelImportedPreviewScale")
        self.formLayoutImportedImage.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.labelImportedPreviewScale)
        self.verticalLayoutImportedImage.addLayout(self.formLayoutImportedImage)
        self.pushButtonImportSingleImage = QtWidgets.QPushButton(self.groupBoxImportedImage)
        self.pushButtonImportSingleImage.setObjectName("pushButtonImportSingleImage")
        self.verticalLayoutImportedImage.addWidget(self.pushButtonImportSingleImage)
        self.pushButtonImportImageSequence = QtWidgets.QPushButton(self.groupBoxImportedImage)
        self.pushButtonImportImageSequence.setObjectName("pushButtonImportImageSequence")
        self.verticalLayoutImportedImage.addWidget(self.pushButtonImportImageSequence)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutImportedImage.addItem(spacerItem1)
        self.horizontalLayoutReferenceImage.addWidget(self.groupBoxImportedImage)
        self.splitterReferenceAndRealImage = QtWidgets.QSplitter(self.tabReferenceImage)
        self.splitterReferenceAndRealImage.setOrientation(QtCore.Qt.Horizontal)
        self.splitterReferenceAndRealImage.setObjectName("splitterReferenceAndRealImage")
        self.groupBoxReferencePreview = QtWidgets.QGroupBox(self.splitterReferenceAndRealImage)
        self.groupBoxReferencePreview.setObjectName("groupBoxReferencePreview")
        self.verticalLayoutReferencePreview = QtWidgets.QVBoxLayout(self.groupBoxReferencePreview)
        self.verticalLayoutReferencePreview.setObjectName("verticalLayoutReferencePreview")
        self.referenceImageView = QtWidgets.QGraphicsView(self.groupBoxReferencePreview)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.referenceImageView.setBackgroundBrush(brush)
        self.referenceImageView.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.referenceImageView.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.referenceImageView.setResizeAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.referenceImageView.setObjectName("referenceImageView")
        self.verticalLayoutReferencePreview.addWidget(self.referenceImageView)
        self.groupBoxRealImagePreview = QtWidgets.QGroupBox(self.splitterReferenceAndRealImage)
        self.groupBoxRealImagePreview.setObjectName("groupBoxRealImagePreview")
        self.verticalLayoutRealImagePreview = QtWidgets.QVBoxLayout(self.groupBoxRealImagePreview)
        self.verticalLayoutRealImagePreview.setObjectName("verticalLayoutRealImagePreview")
        self.realImageView = QtWidgets.QGraphicsView(self.groupBoxRealImagePreview)
        brush = QtGui.QBrush(QtGui.QColor(16, 18, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.realImageView.setBackgroundBrush(brush)
        self.realImageView.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.realImageView.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.realImageView.setResizeAnchor(QtWidgets.QGraphicsView.AnchorViewCenter)
        self.realImageView.setObjectName("realImageView")
        self.verticalLayoutRealImagePreview.addWidget(self.realImageView)
        self.horizontalLayoutReferenceImage.addWidget(self.splitterReferenceAndRealImage)
        self.tabWidgetMain.addTab(self.tabReferenceImage, "")
        self.verticalLayoutMain.addWidget(self.tabWidgetMain)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImportSingleImage = QtWidgets.QAction(MainWindow)
        self.actionImportSingleImage.setObjectName("actionImportSingleImage")
        self.actionImportImageSequence = QtWidgets.QAction(MainWindow)
        self.actionImportImageSequence.setObjectName("actionImportImageSequence")
        self.menuFile.addAction(self.actionImportSingleImage)
        self.menuFile.addAction(self.actionImportImageSequence)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidgetMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MeteoAlign Phase 2"))
        self.groupBoxObserver.setTitle(_translate("MainWindow", "观测信息"))
        self.labelObservationTime.setText(_translate("MainWindow", "拍摄时间"))
        self.dateTimeEditObservation.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd HH:mm:ss"))
        self.labelUtcOffset.setText(_translate("MainWindow", "UTC 偏移"))
        self.doubleSpinBoxUtcOffset.setSuffix(_translate("MainWindow", " h"))
        self.labelLatitude.setText(_translate("MainWindow", "纬度"))
        self.doubleSpinBoxLatitude.setSuffix(_translate("MainWindow", " deg"))
        self.labelLongitude.setText(_translate("MainWindow", "经度"))
        self.doubleSpinBoxLongitude.setSuffix(_translate("MainWindow", " deg"))
        self.labelElevation.setText(_translate("MainWindow", "海拔"))
        self.doubleSpinBoxElevation.setSuffix(_translate("MainWindow", " m"))
        self.groupBoxCamera.setTitle(_translate("MainWindow", "相机参数"))
        self.labelSensorWidth.setText(_translate("MainWindow", "传感器宽"))
        self.doubleSpinBoxSensorWidth.setSuffix(_translate("MainWindow", " mm"))
        self.labelSensorHeight.setText(_translate("MainWindow", "传感器高"))
        self.doubleSpinBoxSensorHeight.setSuffix(_translate("MainWindow", " mm"))
        self.pushButtonSwapOrientation.setText(_translate("MainWindow", "切换横/竖幅构图"))
        self.labelImageWidth.setText(_translate("MainWindow", "导出图像宽"))
        self.spinBoxImageWidth.setSuffix(_translate("MainWindow", " px"))
        self.labelImageHeight.setText(_translate("MainWindow", "导出图像高"))
        self.spinBoxImageHeight.setSuffix(_translate("MainWindow", " px"))
        self.labelFocalLength.setText(_translate("MainWindow", "焦距"))
        self.doubleSpinBoxFocalLength.setSuffix(_translate("MainWindow", " mm"))
        self.labelLensModel.setText(_translate("MainWindow", "镜头类型"))
        self.comboBoxLensModel.setItemText(0, _translate("MainWindow", "普通广角透视"))
        self.comboBoxLensModel.setItemText(1, _translate("MainWindow", "等距鱼眼"))
        self.comboBoxLensModel.setItemText(2, _translate("MainWindow", "等立体角鱼眼"))
        self.labelFisheyeFov.setText(_translate("MainWindow", "鱼眼视场"))
        self.doubleSpinBoxFisheyeFov.setSuffix(_translate("MainWindow", " deg"))
        self.labelMagLimit.setText(_translate("MainWindow", "极限星等"))
        self.doubleSpinBoxMagLimit.setSuffix(_translate("MainWindow", " mag"))
        self.groupBoxDisplay.setTitle(_translate("MainWindow", "显示选项"))
        self.labelCommonNameLimit.setText(_translate("MainWindow", "俗名阈值"))
        self.labelCommonNameLimitValue.setText(_translate("MainWindow", "1.0 mag"))
        self.groupBoxView.setTitle(_translate("MainWindow", "视野方向"))
        self.labelAz.setText(_translate("MainWindow", "中心方位角"))
        self.doubleSpinBoxAz.setSuffix(_translate("MainWindow", " deg"))
        self.labelAlt.setText(_translate("MainWindow", "中心高度"))
        self.doubleSpinBoxAlt.setSuffix(_translate("MainWindow", " deg"))
        self.labelRoll.setText(_translate("MainWindow", "Roll"))
        self.doubleSpinBoxRoll.setSuffix(_translate("MainWindow", " deg"))
        self.groupBoxReference.setTitle(_translate("MainWindow", "参考图"))
        self.labelReferenceStarCount.setText(_translate("MainWindow", "标注星数"))
        self.spinBoxReferenceStarCount.setSuffix(_translate("MainWindow", " 颗"))
        self.pushButtonExportReference.setText(_translate("MainWindow", "确定参考图并导出"))
        self.pushButtonRender.setText(_translate("MainWindow", "重新渲染"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabSimulator), _translate("MainWindow", "星空模拟"))
        self.groupBoxImportedImage.setTitle(_translate("MainWindow", "真实图像"))
        self.labelImportedImagePathTitle.setText(_translate("MainWindow", "文件"))
        self.labelImportedImagePath.setText(_translate("MainWindow", "未导入"))
        self.labelImportedImageSizeTitle.setText(_translate("MainWindow", "原始尺寸"))
        self.labelImportedImageSize.setText(_translate("MainWindow", "-"))
        self.labelImportedPreviewSizeTitle.setText(_translate("MainWindow", "预览尺寸"))
        self.labelImportedPreviewSize.setText(_translate("MainWindow", "-"))
        self.labelImportedPreviewScaleTitle.setText(_translate("MainWindow", "预览比例"))
        self.labelImportedPreviewScale.setText(_translate("MainWindow", "-"))
        self.pushButtonImportSingleImage.setText(_translate("MainWindow", "导入单张图像"))
        self.pushButtonImportImageSequence.setText(_translate("MainWindow", "导入序列图像"))
        self.groupBoxReferencePreview.setTitle(_translate("MainWindow", "参考星图"))
        self.groupBoxRealImagePreview.setTitle(_translate("MainWindow", "真实图像预览"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tabReferenceImage), _translate("MainWindow", "真实图像点选"))
        self.menuFile.setTitle(_translate("MainWindow", "文件"))
        self.actionImportSingleImage.setText(_translate("MainWindow", "导入单张图像..."))
        self.actionImportImageSequence.setText(_translate("MainWindow", "导入序列图像..."))
